Practical Machine Learning Project

Background

Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about 
personal activity relatively inexpensively. These type of devices are part of the quantified self movement – a group 
of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their 
behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular 
activity they do, but they rarely quantify how well they do it. In this project, your goal will be to use data from 
accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts 
correctly and incorrectly in 5 different ways. More information is available from the website 
here: http://groupware.les.inf.puc-rio.br/har (see the section on the Weight Lifting Exercise Dataset). 

Data 

The training data for this project are available here: 

https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv

The test data are available here: 

https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv

The data for this project come from this source: http://groupware.les.inf.puc-rio.br/har. If you use the document you 
create for this class for any purpose please cite them as they have been very generous in allowing their data to be 
used for this kind of assignment. 

For consistency of data features, perform the steps mentioned below:

  Conversion of empty strings to NA values.
  
  Removal of excel division error strings #DIV/0! and replace with NA values.
  

Prepare the data needed for further processing.

Select the Features to be Presented

Extract only the useful information and what are important in this study. That is, remove all NA values.

Do the validation of the data.

Partition the data for test and training. Then do the prediction using Random Forest Model.

########################################
myprogram.R
https://github.com/github722105/pmlproject/blob/master/myprogram.R

Please apply the machine learning algorithm you built to each of the 20 test cases in the testing data set. For more information and instructions on how to build your model see the prediction assignment writeup. For each test case you should submit a text file with a single capital letter (A, B, C, D, or E) corresponding to your prediction for the corresponding problem in the test data set. You get 1 point for each correct answer. You may submit up to 2 times for each problem. I know it is a lot of files to submit. It may be helpful to use the following function to create the files. If you have a character vector with your 20 predictions in order for the 20 problems. So something like (note these are not the right answers!):

answers = rep("A", 20)
then you can load this function by copying and pasting it into R:
 
pml_write_files = function(x){
  n = length(x)
  for(i in 1:n){
    filename = paste0("problem_id_",i,".txt")
    write.table(x[i],file=filename,quote=FALSE,row.names=FALSE,col.names=FALSE)
  }
}
then create a folder where you want the files to be written. Set that to be your working directory and run:
 
pml_write_files(answers)

#   Prediction Results

# 01  B, 02  A, 03  B, 04  A, 05  A, 06  E, 07  D, 08  B, 09  A, 10  A, 
# 11  B, 12  C, 13  B, 14  A, 15  E, 16  E, 17  A, 18  B, 19  B, 20  B 

# Levels: A B C D E
